apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres01
  labels:
    app: postgres01
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres01
        role: master
    spec:
      containers:
      - name: postgres01
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "Password123!"
        volumeMounts:
        - name: pgvolume01
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgvolume01
        scaleIO:
          gateway: https://192.168.50.12:443/api
          volumeName: pgdata-k8-01
          system: cluster1
          protectionDomain: pdomain
          storagePool: pool1
          secretRef:
            name: sio-secret
