# -*- mode: ruby -*-
# vi: set ft=ruby :

# This configuration requires Vagrant 1.5 or newer and two plugins:
#
#   vagrant plugin install vagrant-hosts        ~> 2.1.4
#   vagrant plugin install vagrant-auto_network ~> 1.0.0
#

Vagrant.require_version ">= 1.5.0"
require 'vagrant-hosts'
require 'vagrant-auto_network'
require 'vagrant-persistent-storage'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

CHEF_SERVER_SCRIPT = <<EOF.freeze
  apt-get update
  apt-get -y install curl

  # ensure the time is up to date
  echo "Synchronizing time..."
  apt-get -y install ntp
  service ntp stop
  ntpdate -s time.nist.gov
  service ntp start

  # download the Chef server package
  echo "Downloading the Chef server package..."
  if [ ! -f /downloads/chef-server-core_12.11.1_amd64.deb  ]; then
    wget -nv -P /downloads https://packages.chef.io/files/stable/chef-server/12.11.1/ubuntu/14.04/chef-server-core_12.11.1-1_amd64.deb
  fi

  # install the package
  echo "Installing Chef server..."
  sudo dpkg -i /downloads/chef-server-core_12.11.1-1_amd64.deb

  # reconfigure and restart services
  echo "Reconfiguring Chef server..."
  sudo chef-server-ctl reconfigure
  echo "Restarting Chef server..."
  sudo chef-server-ctl restart

  # wait for services to be fully available
  echo "Waiting for services..."
  until (curl -D - http://localhost:8000/_status) | grep "200 OK"; do sleep 15s; done
  while (curl http://localhost:8000/_status) | grep "fail"; do sleep 15s; done

  # create admin user
  echo "Creating a user and organization..."
  sudo chef-server-ctl user-create admin Bob Admin admin@4thcoffee.com insecurepassword --filename admin.pem
  sudo chef-server-ctl org-create 4thcoffee "Fourth Coffee, Inc." --association_user admin --filename 4thcoffee-validator.pem

  # copy admin RSA private key to share
  echo "Copying admin key to /vagrant/secrets..."
  mkdir -p /vagrant/secrets
  cp -f /home/vagrant/admin.pem /vagrant/secrets

  echo "Your Chef server is ready!"
EOF

NODE_SCRIPT = <<EOF.freeze
  echo "Preparing node..."

  # ensure the time is up to date
  yum -y install ntp
  systemctl start ntpd
  systemctl enable ntpd

  echo "10.1.1.33 chef-server.test" | tee -a /etc/hosts
EOF

def set_hostname(server)
  server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end

Vagrant.configure(2) do |config|

  config.vm.define 'chef-server' do |cs|
    cs.vm.box = 'bento/ubuntu-14.04'
    cs.vm.box_version = '2.2.9'
    cs.vm.hostname = 'chef-server.test'
    cs.vm.network 'private_network', ip: '10.1.1.33'
    cs.vm.provision 'shell', inline: CHEF_SERVER_SCRIPT.dup
    set_hostname(cs)

    cs.vm.provider 'virtualbox' do |v|
      v.memory = 2048
      v.cpus = 2
    end

  end

  [
    ['centos1', '10.1.1.34'],
    ['centos2', '10.1.1.35'],
    ['centos3', '10.1.1.36'],
    ['centos4', '10.1.1.37']
  ].each do |hostname, ip|
    config.vm.define hostname do |n|
      n.vm.box = 'bento/centos-7.2'
      n.vm.box_version = '2.2.9'
      n.vm.hostname = hostname
      n.vm.network 'private_network', ip: ip
      n.vm.provision :shell, inline: NODE_SCRIPT.dup

      n.persistent_storage.enabled = true
      n.persistent_storage.location = "#{hostname}_hdd2.vdi"
      n.persistent_storage.size = 100_000
      n.persistent_storage.use_lvm = false

      set_hostname(n)

      n.vm.provider 'virtualbox' do |v|
        v.memory = 1024
        v.cpus = 2
      end

    end

  end

end

