# Created by Jonas Rosland, @virtualswede & Matt Cowger, @mcowger
# Many thanks to this post by James Carr: http://blog.james-carr.org/2013/03/17/dynamic-vagrant-nodes/

# vagrant box
vagrantbox="centos_7.1"

# vagrant box url
vagrantboxurl="https://github.com/CommanderK5/packer-centos-template/releases/download/0.7.1/vagrant-centos-7.1.box"

# scaleio admin password
password="Scaleio123"
# add your domain here
domain = 'scaleio.local'

# add your nodes here
nodes = ['tb', 'mdm1', 'mdm2']

# add your IPs here
network = "192.168.50"

clusterip = "#{network}.10"
tbip = "#{network}.11"
firstmdmip = "#{network}.12"
secondmdmip = "#{network}.13"

# Install ScaleIO cluster automatically or IM only
#If True a fully working ScaleIO cluster is installed. False mean only IM is installed on node MDM1.
if ENV['SCALEIO_CLUSTER_INSTALL']
  clusterinstall = ENV['SCALEIO_CLUSTER_INSTALL'].to_s.downcase
else
  clusterinstall = "true"
end

# Install Docker automatically
if ENV['SCALEIO_DOCKER_INSTALL']
  dockerinstall = ENV['SCALEIO_DOCKER_INSTALL'].to_s.downcase
else
  dockerinstall = "true"
end

# Install REX-Ray automatically
if ENV['SCALEIO_REXRAY_INSTALL']
  rexrayinstall = ENV['SCALEIO_REXRAY_INSTALL'].to_s.downcase
else
  rexrayinstall = "true"
end

# Install and Configure Docker Swarm Automatically
if ENV['SCALEIO_SWARM_INSTALL']
  swarminstall = ENV['SCALEIO_SWARM_INSTALL'].to_s.downcase
else
  swarminstall = "false"
end

# Install and Configure Mesos Automatically
if ENV['SCALEIO_MESOS_INSTALL']
  mesosinstall = ENV['SCALEIO_MESOS_INSTALL'].to_s.downcase
else
  mesosinstall = "false"
end

# Verify that the ScaleIO package has the correct size
if ENV['VERIFYFILES']
  verifyfiles = ENV['VERIFYFILES'].to_s.downcase
else
  verifyfiles = "true"
end

# version of installation package
version = "2.0-0.0"

#OS Version of package
os="el7"

#ZIP OS Version of package
zip_os="OEL7"

# installation folder
siinstall = "/opt/scaleio/siinstall"

# packages folder
packages = "/opt/scaleio/siinstall/ECS/packages"
# package name, was ecs for 1.21, is now EMC-ScaleIO from 1.30
packagename = "EMC-ScaleIO"

# fake device
device = "/home/vagrant/scaleio1"

# loop through the nodes and set hostname
scaleio_nodes = []
subnet=10
nodes.each { |node_name|
  (1..1).each {|n|
    subnet += 1
    scaleio_nodes << {:hostname => "#{node_name}"}
  }
}

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-proxyconf")
    #config.proxy.http     = "http://proxy.example.com:3128/"
    #config.proxy.https    = "http://proxy.example.com:3128/"
    #config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
  #config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  scaleio_nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = "#{vagrantbox}"
      node_config.vm.box_url = "#{vagrantboxurl}"
      node_config.vm.host_name = "#{node[:hostname]}.#{domain}"
      node_config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end

      if node[:hostname] == "mdm1"
        node_config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "3072"]
        end

        node_config.vm.network "private_network", ip: "#{firstmdmip}"
        # node_config.vm.network "forwarded_port", guest: 6611, host: 6611
        node_config.vm.provision "shell" do |s|
          s.path = "scripts/mdm1.sh"
          s.args = "-o #{os} -zo #{zip_os} -v #{version} -n #{packagename} -d #{device} -f #{firstmdmip} -s #{secondmdmip} -tb #{tbip} -i #{siinstall} -p #{password} -c #{clusterinstall} -dk #{dockerinstall} -r #{rexrayinstall} -ds #{swarminstall} -ms #{mesosinstall}"
        end
      end

      if node[:hostname] == "tb"
        node_config.vm.network "private_network", ip: "#{tbip}"
        node_config.vm.provision "shell" do |s|
          s.path = "scripts/tb.sh"
          s.args = "-o #{os} -zo #{zip_os} -v #{version} -n #{packagename} -d #{device} -f #{firstmdmip} -s #{secondmdmip} -tb #{tbip} -i #{siinstall} -c #{clusterinstall} -dk #{dockerinstall} -r #{rexrayinstall} -ds #{swarminstall} -ms #{mesosinstall} -vf #{verifyfiles}"
        end
      end

      if node[:hostname] == "mdm2"
        node_config.vm.network "private_network", ip: "#{secondmdmip}"
        node_config.vm.provision "shell" do |s|
          s.path = "scripts/mdm2.sh"
          s.args = "-o #{os} -zo #{zip_os} -v #{version} -n #{packagename} -d #{device} -f #{firstmdmip} -s #{secondmdmip} -tb #{tbip} -i #{siinstall} -p #{password} -c #{clusterinstall} -dk #{dockerinstall} -r #{rexrayinstall} -ds #{swarminstall} -ms #{mesosinstall}"
        end
      end
    end
  end
end
